# Generated by Django 4.2.5 on 2023-09-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='course_name',
            field=models.TextField(default='TA'),
        ),
    ]
