# Generated by Django 4.2.5 on 2023-09-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='course_name',
        ),
    ]
